---
- name: Copy php upstream conf
  copy:
    src=php-upstream.conf
    dest=/etc/nginx/conf.d/php-upstream.conf
    owner={{ deploy_user }}
    group={{ deploy_user }}
  notify:
    - restart nginx

- name: Check wordpress configs directory
  file:
    dest=/etc/nginx/global/
    owner={{ deploy_user }}
    group={{ deploy_user }}
    state=directory

- name: Copy wordpress configs
  copy:
    src={{ item }}
    dest=/etc/nginx/global/{{ item }}
    owner={{ deploy_user }}
    group={{ deploy_user }}
  with_items:
  - restrictions.conf
  - wordpress-ms-subdir.conf
  notify:
    - restart nginx
