---
- name: Install common packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
  - python-apt
  - zsh
  - git
  - whois
  - vim
  - most
  - language-pack-ru
  - mc
  - build-essential
  - curl
  - libssl-dev
  - htop
  - libmagick++-dev

- name: Generate RU UTF8 locale
  locale_gen: name=ru_RU.UTF-8 state=present

- include: users.yml
- include: ssh.yml
- include: oh-my-zsh.yml
