---
- name: Install MySQL packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_expire }}
  with_items:
  - mysql-server
  - mysql-client
  - mysqltuner
  notify:
    - restart mysql
