---
- name: Add latest PHP repo
  apt_repository: repo='ppa:ondrej/php5-5.6'
- name: Install PHP packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_expire }}
  with_items:
  - php5
  - php5-gd
  - php5-fpm
  - php5-cli
  - php5-curl
  - php5-mysql
  - php5-mcrypt
  - php5-imagick
  - php5-memcache
  - php5-readline
  notify:
    - restart php-fpm

- include: php-fpm.yml
