---
- name: Add latest PHP repo
  apt_repository: repo='ppa:ondrej/php5-5.6'
- name: Install PHP packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_expire }}
  with_items:
  - php5
  - php5-gd
  - php5-fpm
  - php5-cli
  - php5-curl
  - php5-mysql
  - php5-mcrypt
  - php5-imagick
  - php5-memcache
  - php5-readline
  notify:
    - restart php-fpm

- name: Permit deploy user to restart php-fpm
  lineinfile:
    dest=/etc/sudoers
    regexp="^{{deploy_user}}"
    line="{{ deploy_user }}\tALL=NOPASSWD:\t/usr/sbin/service php5-fpm restart"
    state=present

- name: Install composer
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"

- name: Permit deploy user run composer
  file:
    path=/usr/local/bin/composer
    state=file
    owner={{ deploy_user }}
    group={{ deploy_user }}

- include: php-fpm.yml
