---
- name: Install PHP packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
  - php5
  - php5-gd
  - php5-fpm
  - php5-cli
  - php5-curl
  - php5-mysql
  - php5-mcrypt
  - php5-imagick
  - php5-memcache
  - php5-readline
